# Generated by Django 4.1.7 on 2023-04-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_name', models.CharField(max_length=200, null=True)),
                ('flight_UID', models.CharField(max_length=200, null=True)),
                ('flight_duration', models.DurationField(null=True)),
                ('flight_day_start', models.DateField(null=True)),
                ('flight_hour_start', models.TimeField(null=True)),
                ('flight_day_end', models.DateField(null=True)),
                ('flight_hour_end', models.TimeField(null=True)),
                ('From', models.CharField(max_length=200, null=True)),
                ('To', models.CharField(max_length=200, null=True)),
                ('flight_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
