# Generated by Django 4.1.7 on 2023-04-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='available',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
