# Generated by Django 4.1.7 on 2023-04-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_flight_flight_day_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_duration',
            field=models.FloatField(null=True),
        ),
    ]
