# Generated by Django 4.1.7 on 2023-05-03 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_a_passenger_phone'),
        ('dashboard', '0004_alter_flight_flight_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbr_days_stay', models.IntegerField(blank=True, null=True)),
                ('extra_baggage', models.BooleanField(blank=True, null=True)),
                ('meal', models.BooleanField(blank=True, null=True)),
                ('preffered_seat', models.BooleanField(blank=True, null=True)),
                ('nbr_seat', models.IntegerField(blank=True, null=True)),
                ('state', models.BooleanField(blank=True, null=True)),
                ('flight', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.flight')),
                ('passenger', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationFlightPredictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(blank=True, null=True)),
                ('reservationFlight', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.reservationflight')),
            ],
        ),
    ]
