# Generated by Django 4.1.7 on 2023-05-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_reservationflight_orign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='type',
        ),
        migrations.AddField(
            model_name='reservationflight',
            name='sales_channel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reservationflight',
            name='type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
