# Generated by Django 4.1.7 on 2023-05-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_flight_type_reservationflight_sales_channel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationflight',
            old_name='nbr_days_stay',
            new_name='number_of_chair',
        ),
        migrations.RenameField(
            model_name='reservationflight',
            old_name='orign',
            new_name='origin',
        ),
        migrations.RenameField(
            model_name='reservationflight',
            old_name='type',
            new_name='trip_type',
        ),
        migrations.AddField(
            model_name='reservationflight',
            name='travel_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
