# Generated by Django 4.1.7 on 2023-05-07 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_rename_nbr_days_stay_reservationflight_number_of_chair_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationflight',
            old_name='nbr_seat',
            new_name='number_of_chairs_to_reserve',
        ),
    ]
