# Generated by Django 4.1.7 on 2023-05-09 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_a_passenger_phone'),
        ('dashboard', '0011_alter_reservationflightpredictions_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationflight',
            name='flight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.flight'),
        ),
        migrations.AlterField(
            model_name='reservationflight',
            name='passenger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.passenger'),
        ),
    ]
