# Generated by Django 4.1.7 on 2023-04-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
