# Generated by Django 4.1.7 on 2023-04-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_passenger_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='phone',
        ),
        migrations.AddField(
            model_name='passenger',
            name='a',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
